### ISSUE TITLE
UNIX patcher Sharpii command error - line 61 exit code 137

### ISSUE THREAD

**Issue by catoctin** [RiiConnect24/RiiConnect24-Patcher#114]
Hi guys,

I am having an issue where the RC24 patcher crashes right after I select the option to patch all the apps. Currently using the latest  version (v1.1.3) of the patcher as of 5/20/2022. I'm using macOS 12 Monterey on an M1 Mac using Terminal. Seems like there's no current issue here about the specific line and error code. Here's the terminal output:

`Unix RiiConnect24 Patcher v1.1.3
By HTV04 and SketchMaster2001

====ERROR=======================================================================

An error has occurred.

ERROR DETAILS:
	* Task: 
	* Command: ./Sharpii nusd -ios ${1} -v ${2} -o 
Temp/Working/Wii/IOS${1}/Temp.wad -wad -q
	* Line: 61
	* Exit code: 137

Open an issue on https://github.com/RiiConnect24/RiiConnect24-Patcher/issues 
regarding your error. Alternatively, contact either HTV04 #4802 or 
SketchMaster2001 #8837 on Discord.`

any help appreciated, thanks

**Comment by TheShadowEevee** [comment]
Thanks for reporting this! This may be an out of memory error caused by the M1 Mac specific Sharpii binary used, can you try [this patcher](https://raw.githubusercontent.com/TheShadowEevee/RiiConnect24-Patcher/master/RiiConnect24Patcher.sh) and see if that works? If so please let me know! It's the same as the current patcher but with a quick fix I made on my fork of the project.

If the patcher doesn't download when you click the link you may need to right click the page and click "Save As".

**Comment by catoctin** [comment]
> Thanks for reporting this! This may be an out of memory error caused by the M1 Mac specific Sharpii binary used, can you try [this patcher](https://raw.githubusercontent.com/TheShadowEevee/RiiConnect24-Patcher/master/RiiConnect24Patcher.sh) and see if that works? If so please let me know! It's the same as the current patcher but with a quick fix I made on my fork of the project.
> 
> If the patcher doesn't download when you click the link you may need to right click the page and click "Save As".

This patcher worked! No errors whatsoever. Thanks a lot.
