### ISSUE TITLE
Command: ./patch-images.sh  Line:178  Exit code:127.  UNIX problem (MacOS Catalina 10.15.7)

### ISSUE THREAD

**Issue by Miguelitus02** [RiiConnect24/RiiConnect24-Patcher#167]
So, I tried to patch 2 ISOs with the patcher and it sent me this error:

ERROR DETAILS:
	* Task: 
	* Command: ./patch-images.sh
	* Line: 178
	* Exit code: 127

Does anyone know how to overpass this?
Thanks.

**Comment by Naim2000** [comment]
Unsure why the patcher ever had this option. Just [use the official Wiimmfi ISO Patcher](https://wiimmfi.de/patcher/iso).
Or don't. The ISO patcher is pretty redundant because you can [use the Wiimmfi Auto Patcher on Dolphin](https://naim2000.github.io/guides/dolphin/wiimmfi-autopatcher) or [automatic patching using USB loaders on Wii](https://wiimmfi.de/patcher/usbloader).
