### ISSUE TITLE
Patched EVC.wad not generated on MacOS

### ISSUE THREAD

**Issue by gingerbeardman** [RiiConnect24/RiiConnect24-Patcher#18]
1. Run patcher
2. choose "cannot connect SD"
3. inspect wads folder afterwards

Expected
- should contain EVC, 31, 80

Actual
- contains only 31, 80

Workaround:
- I had to use Windows 7 VM to do it.

**Comment by KcrPL** [comment]
I would like to help you but I can't because I made the Windows patcher.

All I can say - the Unix patcher is kinda buggy.

**Comment by larsenv** [comment]
Yeah, the Unix version is broken in a few ways, considering that we make you install Mono to load a C# program is annoying and I'm not sure what we should do to make it better. Sorry.

**Comment by gingerbeardman** [comment]
I think just discontinue the non-Windows versions if they don't work.

**Comment by KcrPL** [comment]
We need a non-Windows patcher.

**Comment by larsenv** [comment]
Being a native Mac user myself, it would be beneficial if this was fixed.

**Comment by gingerbeardman** [comment]
Of course, until then please put a note on the Mac download that it does not work? To prevent people like myself wasting time on it. Thanks!

**Comment by larsenv** [comment]
I guess we could do that, the thing is that based on my setup the patcher seemed to work.

**Comment by InternalLoss** [comment]
It'd be awesome if you could give us the console output for the script ^^

**Comment by Pysis868** [comment]
Got my script to work.
I already had the IOS WADs so I just renamed them, put them in the right place by looking at the script, renamed them, and executed the manual process.

It might break at the patches stage because I think the patches in the KcrPL.github.io repo are now prefixed with 'w' for the Wii versions.

There was some other difference that seemed to be from an update that might break, but can't remember, and it's strange because I think this repo is newer by commits than IOS-Patcher, but you could look at that one to see if it works better for you.

Was following the wii.guide website: https://wii.guide/riiconnect24.

Oh, and the last step with `Sharpii ... -f` could not handle a space in the full path, so I ran the command manually to another directory like `$TMPDIR`.
