### ISSUE TITLE
Make the language selection the first screen that appears when running the batch script

### ISSUE THREAD

**Issue by 2secslater** [RiiConnect24/RiiConnect24-Patcher#37]
I've noticed someone on the Discord server who was having a hard time navigating the patcher as when you start it, it gives you options in English. And, English not being their best language, they were asking for help on the Discord server.

I think the patcher will be more accessible if it asks for the language right away, before throwing you right into an English menu.

**Comment by KcrPL** [comment]
What a great idea!

Unfortunately, about a year or two ago in the predecessor to RiiConnect24 Patcher - [IOS-Patcher](https://github.com/RiiConnect24/IOS-Patcher/releases) I thought about the same.

Unfortunately, I'm aware that software localization is really good and useful but in batch, it's so messy.

Of course, it would work - it's just that for me - working with the patcher after adding languages was hard because the entire patcher changes from text to %variables%.

And well... I need someone to translate it.

Also, what if I won't be able to contact creators of the translation after I add something?

So for now, we're staying with English only. But who knows? Maybe in the future.

**Comment by Sagevonsuper** [comment]
Well that sucks...I hope there's more languages from the patcher someday.
