### ISSUE TITLE
Trying to use Unix patcher on Mac, need xdelta3 command.

### ISSUE THREAD

**Issue by jaylowjaylow** [RiiConnect24/RiiConnect24-Patcher#68]
Hello all,

I originally had an issue with permission. Fixed it with chmod +x. Now I need xdelta3. Here's the error that I get when I try to run the patcher.

"xdelta3" command not found! Please install the "xdelta3" package using your 
package manager.

**Comment by SketchMaster2001** [comment]
Do you have brew installed on your Mac?

**Comment by HTV04** [comment]
Yeah, that's something I've talked with Sketch about before, we need to make a setup guide that includes instructions for installing the needed dependencies on macOS.

I already have a partial setup guide for Linux, but I need to add a macOS section to it. In the meantime, look up how to install Homebrew, then use it to install xdelta3.

**Comment by Artuto** [comment]
Can you not just download binaries like on the Windows version

**Comment by HTV04** [comment]
We *could* (I think), but it's probably better to have the user download it using Homebrew, since I think the Homebrew team maintains and updates the binary anyway.

**Comment by larsenv** [comment]
After installing [brew](https://brew.sh/):

```brew install xdelta```

That's all there is to it!

**Comment by SketchMaster2001** [comment]
I guess I could find the binaries and put them on my repo

**Comment by SketchMaster2001** [comment]
I'm closing this because Larsen already answered the question

**Comment by jaylowjaylow** [comment]
Hello everyone. Just wanted to say I was successful in getting this to run. There were a number of issues that made it tricky. Installing homebrew required me to download xcode from apple. Homebrew also asked for xcode command line tools to be installed, however, Apple moved the location of them and I don't think homebrew has updated their code accordingly. I had to manually locate, download, and install xcode and the command line tools myself before I could install homebrew and xdelta3. As a result, it's not the most user friendly experience. Either something to note in your guide or a reason to look at a different method. Anyway, thanks again for all your help here. Cheers!

**Comment by ntakebay** [comment]
On Mac OS-X, this gives the following error because patchios() is called before the script checks if it is installed (l. 1127).  I think it would be nicer to check if xdelta is installed or not earlier in the script, so users get a more descriptive error message.  This is with v.1.1.0 beta.

ERROR DETAILS:
	* Task: 
	* Command: xdelta3 -d -f -s Temp/Working/Wii/IOS${1}/00000006.app 
Temp/Files/Patcher/Wii/IOS${1}/00000006.delta Temp/Working/Wii/IOS${1}/00000006_patched.app
	* Line: 61
	* Exit code: 127

**Comment by HTV04** [comment]
Reopened because there still seems to be issues with proper xdelta3 installations.

Sorry about that, xdelta3 is supposed to be checked for when the script starts, but it seems that the current implementation is quickly overridden by the main menu because there's no pause. I'll fix this for my next commit.

**Comment by SketchMaster2001** [comment]
It's still open for some reason lol. Closing because fixed
