### ISSUE TITLE
"An error has occurred." in Terminal on Mac.

### ISSUE THREAD

**Issue by kmannumber1** [RiiConnect24/RiiConnect24-Patcher#86]
ERROR DETAILS:
	* Task: 
	* Command: curl --create-dirs -f -k -L -o "${2}" -S -s --insecure 
https://patcher.rc24.xyz/update/RiiConnect24-Patcher/v1/${1}
	* Line: 47
	* Exit code: 35

**Comment by TheShadowEevee** [comment]
Curl has a variety of possible reasons for returning exit code 35. Please follow these steps to hopefully fix the issue.

1. Ensure your internet is working
2. Update your curl package via your package manager
3. Ensure that your internet is not timing out. This can happen due to slow internet, bad connection, or even firewalls.

**Comment by kmannumber1** [comment]
closing, as is patched with another pc.
