### ISSUE TITLE
Linux Terminal error (32-bit Chromebook)

### ISSUE THREAD

**Issue by Kirbz7** [RiiConnect24/RiiConnect24-Patcher#87]
It was loading fine until I came to this point. 

ERROR DETAILS:
        * Task: 
        * Command: ./Sharpii nusd -ios ${1} -v ${2} -o Temp/Working/Wii/IOS${1}/Temp.wad -wad -q
        * Line: 64
        * Exit code: 127

Can someone help?

**Comment by TheShadowEevee** [comment]
Error code 127 generally suggests the command couldn't be found or run; in this case rightly so. Sharpii has no 32-bit Unix binary due to lack of support on the .Net Core side. If you haven't yet resolved this I would email the RiiConnect24 Support and someone there can get you what you need to get RC24 installing.

The support email is: support [at] riiconnect24.net

Thank you for reporting this issue.
